### ISSUE TITLE
Generate shorter output

### ISSUE THREAD

**Issue by CityOfLight77** [rustsmith/rustsmith#3]
Tried rustsmith yesterday and it generates long output. Would love to see rustsmith generate shorter code like [Microsmith Golang](https://github.com/ALTree/microsmith). See the output in the bugs found section

**Comment by mayanksharma3** [comment]
Hi, thanks for trying out RustSmith!

I had a quick look at Microsmith, it seems like microsmith also generates quite long files. For example, I've attached one of the files they generated here [6650802881364220073_main.txt](https://github.com/rustsmith/rustsmith/files/8844032/6650802881364220073_main.txt)

What I think they do is when they find a bug inducing file, they perform test case reduction to find the smallest file that is bug inducing.

For RustSmith currently, test case reduction is done manually but an automatic reduction is something that will be looked into in the near future. However, as rustsmith at its core is just to generate the bug inducing files, they need to be quite large for the chance of bugs being found to be large, just as microsmith does too. 

Hope that makes sense and if you have any other questions let me know!

**Comment by CityOfLight77** [comment]
> 

Thanks, I'm waiting for test case reduction implementation
